# Generated by Django 4.2.11 on 2025-07-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the team name.', max_length=100, unique=True, verbose_name='Team Name')),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo for the team (optional).', null=True, upload_to='team_logos/', verbose_name='Team Logo')),
                ('tournament_points', models.PositiveIntegerField(default=0, verbose_name='Tournament Points')),
                ('match_points', models.PositiveIntegerField(default=0, verbose_name='Match Points')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the player's name or jersey number.", max_length=100, verbose_name='Player Name')),
                ('goals', models.PositiveIntegerField(default=0, help_text='Total goals scored by the player.', verbose_name='Goals Scored')),
                ('yellow_cards', models.PositiveIntegerField(default=0, help_text='Total yellow cards received by the player.', verbose_name='Yellow Cards')),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('is_allowed_to_play', models.BooleanField(default=True, help_text='Indicates if the player is allowed to play in the next match.', verbose_name='Allowed to Play')),
                ('team', models.ForeignKey(help_text='Select the team this player belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournamentapp.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('field', models.CharField(choices=[('8', 'Field 8'), ('9', 'Field 9')], max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournamentapp.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournamentapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournamentapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.team')),
            ],
        ),
    ]
