# Generated by Django 5.2.3 on 2025-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.CharField(choices=[('8', 'Field 8'), ('9', 'Field 9')], max_length=1),
        ),
    ]
