# Generated by Django 5.2.4 on 2025-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0002_field_owner_alter_team_name_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='Main Field', max_length=50, unique=True),
        ),
    ]
