# Generated by Django 4.2.11 on 2025-07-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0002_field_alter_match_start_time_alter_match_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('own_goal', 'Own Goal')], help_text='Type of event that occurred during the match.', max_length=20, verbose_name='Event Type')),
                ('minute', models.PositiveIntegerField(blank=True, help_text='Minute in which the event occurred.', null=True, verbose_name='Minute')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created.', verbose_name='Created At')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournamentapp.match')),
                ('player', models.ForeignKey(blank=True, help_text='Player involved in the event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='tournamentapp.player', verbose_name='Player')),
                ('team', models.ForeignKey(help_text='Team involved in the event.', on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='tournamentapp.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Match Event',
                'verbose_name_plural': 'Match Events',
                'ordering': ['minute', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tournamentapp.matchevent',),
        ),
    ]
