# Generated by Django 5.2.4 on 2025-07-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0003_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tournamentapp.tournament'),
            preserve_default=False,
        ),
    ]
