# Generated by Django 4.2.11 on 2025-07-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0003_matchevent_delete_goal_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='substitute_player',
            field=models.ForeignKey(blank=True, help_text='Only for substitutions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_entries', to='tournamentapp.player'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player involved in the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='tournamentapp.player', verbose_name='Player'),
        ),
    ]
