# Generated by Django 4.2.11 on 2025-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0004_matchevent_substitute_player_alter_matchevent_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tournamentapp.matchevent',),
        ),
        migrations.AddField(
            model_name='player',
            name='own_goals',
            field=models.PositiveIntegerField(default=0, help_text='Total own goals scored by the player.', verbose_name='Own Goals'),
        ),
    ]
