# Generated by Django 5.2.4 on 2025-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0005_tournament_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='public_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=False),
        ),
    ]
