# Generated by Django 4.2.11 on 2025-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0005_delete_goal_goalevent_player_own_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['start_time'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='field',
            name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Team Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Team Name'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'start_time')},
        ),
    ]
