# Generated by Django 5.2.4 on 2025-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0007_alter_tournament_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='Main Field', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'tournament')},
        ),
    ]
