# Generated by Django 4.2.11 on 2025-07-08 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0007_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tournamentapp.field'),
            preserve_default=False,
        ),
    ]
