# Generated by Django 5.2.4 on 2026-03-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0008_alter_field_options_alter_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_allowed_to_play',
        ),
        migrations.RemoveField(
            model_name='player',
            name='own_goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
    ]
