# Generated by Django 5.2.4 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0009_remove_player_goals_remove_player_is_allowed_to_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
