# Generated by Django 5.2.4 on 2026-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0010_tournament_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='points_for_draw',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_for_loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_for_win',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
