# Generated by Django 5.2.4 on 2026-03-23 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0011_tournament_points_for_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='yellow_cards_for_suspension',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
