# Generated by Django 5.2.4 on 2026-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0012_tournament_yellow_cards_for_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_sat_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
