# Generated by Django 5.2.4 on 2026-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0013_player_games_sat_out_player_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout')], default='round_robin', help_text="Tournament format. Only 'round_robin' is implemented currently.", max_length=20),
        ),
    ]
