# Generated by Django 5.2.4 on 2026-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0014_tournament_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin')], default='round_robin', help_text="Tournament format. Only 'round_robin' is implemented currently.", max_length=20),
        ),
    ]
