# Generated by Django 5.2.4 on 2026-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0015_alter_tournament_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='show_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_side_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_vendors',
            field=models.BooleanField(default=True),
        ),
    ]
