# Generated by Django 5.2.4 on 2026-04-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0016_tournament_show_announcements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentapp.field'),
        ),
    ]
