# Generated by Django 5.2.4 on 2026-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentapp', '0017_alter_match_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cache_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
