# Generated by Django 5.2.4 on 2025-09-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournamentapp', '0008_alter_field_options_alter_field_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the banner', max_length=100)),
                ('link_url', models.URLField(blank=True, help_text='Optional link to sponsor website', null=True)),
                ('image', models.ImageField(help_text='Upload sponsor banner image', upload_to='sponsors/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_banners', to='tournamentapp.tournament')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
