# Generated by Django 5.2.4 on 2025-09-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('tournamentapp', '0008_alter_field_options_alter_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorbanner',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='tournamentapp.tournament'),
        ),
    ]
