# Generated by Django 5.2.4 on 2026-02-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsorbanner_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorbanner',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
