# Generated by Django 5.2.4 on 2026-03-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournamentapp', '0015_alter_tournament_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_events', to='tournamentapp.tournament')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
