# Generated by Django 5.2.4 on 2026-03-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='venue_location',
        ),
    ]
